version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: dcs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - '3307:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
