version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: dcs-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: user
    ports:
      - '3307:3307'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
